//! Hirpdag (Hashconsed Immutable Reduced Property Directed Acyclic Graph)
//! data structures, generated by the `#[hirpdag_module]` attribute macro:
//!
//! ```
//! use hirpdag::*;
//!
//! #[hirpdag_module]
//! mod datamodel {
//!     #[hirpdag]
//!     struct Node {
//!         name: String,
//!         children: Vec<Node>,
//!     }
//! }
//! use datamodel::*;
//!
//! fn main() {
//!     let leaf = Node::new("leaf".to_string(), vec![]);
//!     let a = Node::new("parent".to_string(), vec![leaf.clone()]);
//!     let b = Node::new("parent".to_string(), vec![leaf]);
//!     // Hash-consing: structurally equal nodes are the same interned node.
//!     assert_eq!(a, b);
//! }
//! ```
//!
//! The generated code refers to this crate by absolute paths, so no imports
//! are required inside the module; add them only when your own code in the
//! module names hirpdag items.
//!
//! `#[hirpdag_module]` must be an *outer* attribute on an inline module.
//! Rust does not accept proc-macro attributes in inner form
//! (`#![hirpdag_module]`); see rust-lang/rust#54726:
//!
//! ```compile_fail,E0658
//! use hirpdag::*;
//!
//! mod datamodel {
//!     #![hirpdag_module]
//!
//!     #[hirpdag]
//!     struct Node {
//!         v: usize,
//!     }
//! }
//! ```

#![forbid(unsafe_code)]

pub mod base;

pub use hirpdag_hashconsing;

// Re-export #[derive(Hirpdag)]
#[doc(hidden)]
pub use hirpdag_derive::*;

pub use lazy_static::lazy_static;

// Re-exported for use by hirpdag_derive generated code, so that user crates
// do not need to declare these dependencies themselves.
pub use postcard;
pub use serde;
pub use serde_json;
