//! Hirpdag (Hashconsed Immutable Reduced Property Directed Acyclic Graph)
//! data structures, generated by the `#[hirpdag_module]` attribute macro
//! (see its documentation for the attribute arguments):
//!
//! ```
//! use hirpdag::*;
//!
//! #[hirpdag_module]
//! mod datamodel {
//!     #[hirpdag]
//!     struct Node {
//!         name: String,
//!         children: Vec<Node>,
//!     }
//! }
//! use datamodel::*;
//!
//! fn main() {
//!     let leaf = Node::new("leaf".to_string(), vec![]);
//!     let a = Node::new("parent".to_string(), vec![leaf.clone()]);
//!     let b = Node::new("parent".to_string(), vec![leaf]);
//!     // Hash-consing: structurally equal nodes are the same interned node.
//!     assert_eq!(a, b);
//! }
//! ```
//!
//! The inner attribute form is not accepted by Rust (rust-lang/rust#54726):
//!
//! ```compile_fail,E0658
//! use hirpdag::*;
//!
//! mod datamodel {
//!     #![hirpdag_module]
//! }
//! ```

#![forbid(unsafe_code)]

pub mod base;

// The memoization trait a rewriter supplies, re-exported at the crate root so
// a rewriter that disables memoization can name it via `use hirpdag::*`
// (`#[derive(HirpdagMemoize)]` covers the common, memoizing case). The trait and
// the derive macro share a name in different namespaces, like `Clone`.
pub use base::HirpdagMemoize;

pub use hirpdag_hashconsing;

// Re-export #[derive(Hirpdag)]
#[doc(hidden)]
pub use hirpdag_derive::*;

pub use lazy_static::lazy_static;

// Re-exported for use by hirpdag_derive generated code, so that user crates
// do not need to declare these dependencies themselves.
pub use postcard;
pub use serde;
pub use serde_json;
