// Shared benchmark support.
//
// The hash-consing configuration modules themselves are produced by
// `hirpdag::hirpdag_configurations!` (see hirpdag_derive), invoked directly
// in each bench file: proc-macro output uses call-site hygiene, so the
// generated modules behave exactly as if written by hand. A `macro_rules!`
// wrapper cannot do that job — items generated by the hirpdag attribute
// macros from macro-authored tokens are invisible to the caller's code.
//
// This module holds the criterion-side helpers shared by all benches:
// `bench_each_config!` registers a benchmark for a function from each
// configuration module, and `hirpdag_bench_main!` is the shared
// criterion_group/criterion_main boilerplate. The configuration list and
// report labels here must match the `configurations = [...]` lists in the
// bench files.

macro_rules! bench_each_config {
    (@one $group:expr, $params:expr, $function:ident, $module:ident, $label:literal) => {
        $group.bench_with_input(
            criterion::BenchmarkId::new($label, $params),
            &$params,
            |b, params| b.iter(|| crate::$module::$function(std::hint::black_box(params))),
        );
    };
    ($group:expr, $params:expr, $function:ident) => {
        bench_each_config!(@one $group, $params, $function, arc_hash_linear, "ArcHashLinear");
        bench_each_config!(@one $group, $params, $function, arc_hash_sorted, "ArcHashSorted");
        bench_each_config!(@one $group, $params, $function, arc_tovweaktable, "ArcTovWeakTable");
        bench_each_config!(@one $group, $params, $function, leak_hash_linear, "LeakHashLinear");
    };
}

// Criterion group/main boilerplate with the sample size and measurement time
// shared by all hirpdag benchmarks.
macro_rules! hirpdag_bench_main {
    ($($target:ident),+ $(,)?) => {
        criterion::criterion_group! {
            name = benches;
            config = criterion::Criterion::default()
                .sample_size(10)
                .measurement_time(core::time::Duration::from_secs(15));
            targets = $($target),+
        }
        criterion::criterion_main!(benches);
    };
}

use criterion::{measurement::WallTime, AxisScale, BenchmarkGroup, Criterion, PlotConfiguration};

pub fn log_scale_group<'a>(c: &'a mut Criterion, name: &str) -> BenchmarkGroup<'a, WallTime> {
    let mut group = c.benchmark_group(name);
    group.plot_config(PlotConfiguration::default().summary_scale(AxisScale::Logarithmic));
    group
}
