// DAG-aware serialization / deserialization support.
//
// Serializes a hirpdag DAG as a flat list of nodes in topological order
// (dependencies before dependents). Each node's hirpdag-ref fields are
// encoded as integer indices into that list rather than inline data, so
// shared sub-DAGs appear exactly once.
//
// Users must wrap their root node in `HirpdagDag<T>` (generated by
// `#[hirpdag_end]`) to use serde:
//   let json = serde_json::to_string(&HirpdagDag::new(root)).unwrap();
//   let dag: HirpdagDag<MyType> = serde_json::from_str(&json).unwrap();

use crate::base::basic_traits::IsNumber;
use std::any::Any;
use std::collections::{HashMap, HashSet};
use std::sync::Arc;

// ── Collection context ────────────────────────────────────────────────────────

/// Accumulates all nodes reachable from a root, in topological order
/// (dependencies before dependents). The root is always the last entry.
pub struct HirpdagDagCollectCtx {
    pub visited: HashSet<u64>,
    pub id_to_idx: HashMap<u64, usize>,
    /// Type-erased hirpdag refs in topological order.
    pub nodes: Vec<Arc<dyn Any>>,
}

impl HirpdagDagCollectCtx {
    pub fn new() -> Self {
        Self {
            visited: HashSet::new(),
            id_to_idx: HashMap::new(),
            nodes: Vec::new(),
        }
    }
}

// ── Collection trait ──────────────────────────────────────────────────────────

/// Implemented for hirpdag ref types (by the proc-macro) and for common
/// field types (by blanket impls below). Calling `hirpdag_dag_collect` on
/// a hirpdag ref adds all transitive dependencies, then the ref itself, to
/// `ctx` — skipping already-visited nodes.
pub trait HirpdagDagCollect {
    fn hirpdag_dag_collect(&self, ctx: &mut HirpdagDagCollectCtx);
}

// Blanket: numbers are leaves — nothing to collect.
impl<P: IsNumber> HirpdagDagCollect for P {
    fn hirpdag_dag_collect(&self, _ctx: &mut HirpdagDagCollectCtx) {}
}

impl HirpdagDagCollect for String {
    fn hirpdag_dag_collect(&self, _ctx: &mut HirpdagDagCollectCtx) {}
}

impl HirpdagDagCollect for bool {
    fn hirpdag_dag_collect(&self, _ctx: &mut HirpdagDagCollectCtx) {}
}

impl<T: HirpdagDagCollect> HirpdagDagCollect for Option<T> {
    fn hirpdag_dag_collect(&self, ctx: &mut HirpdagDagCollectCtx) {
        if let Some(v) = self {
            v.hirpdag_dag_collect(ctx);
        }
    }
}

impl<T: HirpdagDagCollect> HirpdagDagCollect for Vec<T> {
    fn hirpdag_dag_collect(&self, ctx: &mut HirpdagDagCollectCtx) {
        for v in self {
            v.hirpdag_dag_collect(ctx);
        }
    }
}

// ── Thread-local serialization context ───────────────────────────────────────

std::thread_local! {
    /// Active during `HirpdagDag` serialization. Maps creation_id → flat-list index.
    /// When `Serialize for {Name}` finds this set it emits the index.
    pub static HIRPDAG_DAG_SER_CTX: std::cell::RefCell<Option<HashMap<u64, usize>>>
        = std::cell::RefCell::new(None);

    /// Active during `HirpdagDag` deserialization. Holds already-deserialized
    /// hirpdag refs (in flat-list order). When `Deserialize for {Name}` finds
    /// this set it reads a usize and looks up the ref.
    pub static HIRPDAG_DAG_DESER_CTX: std::cell::RefCell<Option<Vec<Arc<dyn Any>>>>
        = std::cell::RefCell::new(None);
}
