name: CI

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - '**.rs'
    - '**/Cargo.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        default: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose
    - name: UnitTests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --tests
    - name: DocTests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --doc
    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features
    - name: Fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
