name: Test

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - '**.rs'
    - '**/Cargo.*'

jobs:
  test:
    name: Test
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        default: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --all-targets
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --doc
    - uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
